### ISSUE TITLE
[배포] AWS 자동화 배포

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#103]
## ISSUE
- Group: `배포`
- Type: `bug`, `feature`
- Detail: 

## TODO
- [ ] S3
- [ ] 클라이언트 파이프라인 연결
- [ ] 클라이언트 파이프라인 오류 수정#100 참고
- [ ] 서버 파이프라인 연결
- [ ] RDS

## Labels
Estimated time: E: `3h`
Group : `배포`
