### ISSUE TITLE
[프론트엔드, 백엔드, 배포] 각종 버그 및 배포

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#107]
## ISSUE
- Group: `client`, `server`, `배포
- Type: `bug`
- Detail: UserRepository 연결 불가 현상, 갑자기 서버 연결에러 현상 고치기

## TODO
- [x] 갑자기 서버 연결에러 현상 고치기
- [x] UserRepository 연결 불가 현상
- [x] 로드밸런서, cloudFront이용해서 https배포 진행중
- [x] 배포 성공

## Labels
Estimated time: E: `3h`
Group : `client`, `server`,`SR`
