### ISSUE TITLE
[프론트 엔드] 수정 

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#123]
## ISSUE
- Group: `client`
- Type: `bug`, `feature`, `css` 
- Detail: 수정

## TODO
- [ ] favicon 변경
- [ ] favicon 변경 이미지 에러페이지,카카오 로딩페이지 공유
- [ ] Nav 사이드바 크기 CSS 수정
- [ ] Login, Signup 비밀번호 type수정, 속성 추가
- [ ] Comment API 수정

## Labels
Estimated time: E: `3h`
Group : `client`
