### ISSUE TITLE
[프론트 엔드] 반응형 수정

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#128]
## ISSUE
- Group: `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete` ,`css` 등등 
- Detail: fix actions from client redux

## TODO
- [ ] DiayPage CSS 수정
- [ ] Nav CSS 수정
- [ ] Comments/Drawing CSS수정
- [ ] Mypage CSS 수정

## Labels
Estimated time: E: `3h`
Group : `client`
