### ISSUE TITLE
[프론트엔드] 일기 작성 CSS

### ISSUE THREAD

**Issue by Jaekomplett** [soyoung931014/PICKSHARE#45]
## ISSUE
- Group: `client`
- Type: `css`
- Detail: 일기 작성 CSS 구현

## TODO
- [ ] 전체 구획 나누기
- [ ] 대략적인 위치 설정
- [ ] 페이지네이션 애니메이션 구현

## Labels
Estimated time: E: `3h`
Group : `client`
