### ISSUE TITLE
[프론트 엔드] Mypage 프로필 등록 - AWS S3 연결, input 태그 커스텀

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#68]
## ISSUE
- Group: `client`
- Type: `feature`, `css`  
- Detail: 프로필 이미지를 서버가 아닌 aws S3에 저장하고, input 태그의  커스터마이징 해줍니다.

## TODO
- [ ] IAM에서 역할 설정하기
- [ ] Conito로 접근 권한 부여하기
- [ ] S3 버킷 설정하기
- [ ] input 태그 커스텀

## Labels
Estimated time: E: `3h`
Group : `client`
