### ISSUE TITLE
[프론트엔드] 카카오 디벨로퍼 세팅, 로딩페이지 생성,  인가 코드 발급

### ISSUE THREAD

**Issue by soyoung931014** [soyoung931014/PICKSHARE#71]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: 카카오 회원가입시 인가 코드를  발급 받고,  로딩페이지 기능을 구현합니다. (발급받은 인가 코드를 서버에 보내고 유저정보, 토큰을 받아오는 곳)

## TODO
- [x] 카카오 디벨로퍼 세팅
- [x] 카카오 sdk연결 및 카카오 회원 정보 동의 기능 구현
- [x] 로딩페이지 구현(인가코드 받고 서버에 보냄)

## Labels
Estimated time: E: `3h`
Group : `client`
